<a href="https://colab.research.google.com/github/Anantmishra1907/Data-Science-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np


In [7]:
a = np.array([[1 , 3 , 3 ] , [4 , 5 , 6]])
a.shape
print(a)

[[1 3 3]
 [4 5 6]]


In [8]:
b = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8])
print(b)


[1 2 3 4 5 6 7 8]


In [10]:
b[:3]

array([1, 2, 3])

In [11]:
b[0] = 10

In [12]:
print(b)

[10  2  3  4  5  6  7  8]


In [13]:
a.ndim

2

In [15]:
c = np.array([[1, 2, 4], [4, 5, 6], [4, 5, 6]])

In [16]:
c.ndim

2

In [17]:
# creating a basic arrays

In [19]:
np.zeros(2)

array([0., 0.])

In [20]:
np.ones(2)

array([1., 1.])

In [21]:
# empty give me random values it it nor completetly empty

In [22]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
# arange have three steps firstnumber , last number , step

In [25]:
np.arange(4 , 24 , 3)

array([ 4,  7, 10, 13, 16, 19, 22])

here the starting value and last value is gioved into num parts there

In [26]:
np.linspace(0 , 30 , num = 5 )

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [ ]:
# we can specify the data types present there with me

In [29]:
x = np.ones(6, dtype=np.int64)

In [30]:
# Adding , removing and sorting the elements

In [31]:
arr = np.array([1 , 3 , 5 ,6 ,7 , 6 , 8, 7 , 6 ])

In [32]:
np.sort(arr)

array([1, 3, 5, 6, 6, 6, 7, 7, 8])

In [35]:
d = np.array([2 , 4 , 6 , 7])
e = np.array([2 , 5 , 6 , 8 ])
np.concatenate((x , e ) , axis = 0 )

array([1, 1, 1, 1, 1, 1, 2, 5, 6, 8])

In [36]:
f= np.arange(3 , 33 , 2 )

In [40]:
f = np.arange(3, 27, 2) # Creates an array with 12 elements
f.reshape(3, 4)

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [41]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [42]:
b = np.array([[1, 1], [2, 2]])

In [43]:
b.sum(axis = 0 ) # here axis = 0 means coluumns

array([3, 3])

In [44]:
b.sum(axis = 1 ) # here axis = 1 means rows

array([2, 4])

In [45]:
a.max()

np.int64(4)

In [46]:
a.min()

np.int64(1)

In [47]:
a.sum()

np.int64(10)